apply plugin: 'kotlin-android'

// 通用配置
android {
    compileSdk rootProject.ext.android.compileSdk
    defaultConfig {
        // 最低安装版本
        minSdk rootProject.ext.android.minSdk
        // 目标适配版本
        targetSdk rootProject.ext.android.targetSdk
        versionName '1.0'
        versionCode 1
    }
//    // 编译源码版本
//    compileSdkVersion 34
//    defaultConfig {
//        // 最低安装版本
//        minSdkVersion 24
//        // 目标适配版本
//        targetSdkVersion 34
//        versionName '1.0'
//        versionCode 1
//    }
    buildFeatures{
        dataBinding = true
    }
    buildFeatures{
        viewBinding = true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        abortOnError false
        checkReleaseBuilds false
    }


    kotlinOptions {
        jvmTarget = '17'
    }

    // 设置存放 so 文件的目录
    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }

    // 可在 Studio 最左侧中的 Build Variants 选项中切换默认的构建类型
    buildTypes {
        // 调试版本
        debug {}
        // 预览版本
        preview {}
        // 正式版本
        release {}
    }

    // 代码警告配置
    lintOptions {
        // 禁用文本硬编码警告
        disable 'HardcodedText'
        // 禁用图片描述警告
        disable 'ContentDescription'
    }
    buildFeatures {
        buildConfig true
    }


}

afterEvaluate {
//    // 前提条件是这个 Module 工程必须是 Library 类型，并且排除名为 umeng 的 Module 工程
//    if (android.defaultConfig.applicationId == null && "umeng" != getName()) {
//        // 排除 BuildConfig.class
//        generateReleaseBuildConfig.enabled = false
//        generatePreviewBuildConfig.enabled = false
//        generateDebugBuildConfig.enabled = false
//    }
}

dependencies {
    // 依赖 libs 目录下所有的 jar 和 aar 包
    implementation fileTree(include: ['*.jar', '*.aar'], dir: 'libs')
    // AndroidX 库：https://github.com/androidx/androidx
    implementation 'androidx.appcompat:appcompat:1.6.1'
    // Material 库：https://github.com/material-components/material-components-android
    implementation 'com.google.android.material:material:1.10.0'
    // Kotlin 协程：https://github.com/Kotlin/kotlinx.coroutines
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.0'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.0'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.6.1'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.1'
    compileOnly 'androidx.annotation:annotation:1.3.0'

}