apply plugin: 'com.android.library'
apply from: '../../common.gradle'


android {
    namespace 'xyz.doikki.videoplayer.ijk'
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    compileOnly project(':dkplayer-java')
}

ext {
    PUBLISH_ARTIFACT_ID = 'player-ijk'
}

//apply from: '../../publish.gradle'