apply plugin: 'com.android.library'
apply from : '../common.gradle'


android {

    namespace 'xyz.doikki.videocontroller'
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
//    compileOnly project.ext.annotation
    api project(':dkplayer-java')
}

ext {
    PUBLISH_ARTIFACT_ID = 'dkplayer-ui'
}

//apply from: '../publish.gradle'
